version: '3.9'

services:
  bot:
    container_name: bot
    depends_on:
      - postgres
    build: .
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: